### ISSUE TITLE
When will you share the source code?

### ISSUE THREAD

**Issue by GWwangshuo** [lzrobots/DGCNet#2]
Hi, I was wondering when will you share the source code ? Could you please make the source code of this DGCNet publicly accessible rather than just a repository ? Thanks.

Moreover, the idea in this paper is more like the combination of Non-local and Graph Reasoning network GloRe. What's the differences of your method compared with them?

**Comment by MSC19950601** [comment]
Hi, I was wondering when will you share the source code ? Could you please make the source code of this DGCNet publicly accessible rather than just a repository ? Thanks.

Moreover, the idea in this paper is more like the combination of Non-local and Graph Reasoning network GloRe. What's the differences of your method compared with them?

**Comment by wuyang556** [comment]
Hi, I was wondering when will you share the source code ? Could you please make the source code of this DGCNet publicly accessible rather than just a repository ? Thanks.

Moreover, the idea in this paper is more like the combination of Non-local and Graph Reasoning network GloRe. What's the differences of your method compared with them?

**Comment by lxtGH** [comment]
@GWwangshuo @MSC19950601 @wuyang556 . Hi! Sorry for late reply. Our methods is inspried by those works but not simple combination of NL and Glore. Our key insights is to perform simple GCN operation on two independent feature spaces(spatial and channel).  All these NL/GCN-like papers is to capture global/whole images context including OCnet,CCNet,OCRnet. As co-auther, I will release code and model in another repo as soon as possible. https://github.com/lxtGH/GALD-Net. Please keep tuned.

**Comment by lxtGH** [comment]
The code and models have been released.
